//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF354HW01.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Students_DBEntities : DbContext
    {
        public Students_DBEntities()
            : base("name=Students_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<contact_details> contact_details { get; set; }
        public virtual DbSet<emergency_Contacts> emergency_Contacts { get; set; }
        public virtual DbSet<fieldOfStudy> fieldOfStudies { get; set; }
        public virtual DbSet<LogIn_details> LogIn_details { get; set; }
        public virtual DbSet<personal_details> personal_details { get; set; }
    }
}
